/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controlador.Vista_Control;

/**
 *
 * @author ennuikibun
 */
public class Admin_Principal extends javax.swing.JFrame {

    Vista_Control vista_control;
    
    public Admin_Principal(Vista_Control vista) {
        super("Clínica X ~ || Administrador");
        initComponents();
	setLocationRelativeTo(null);
	setSize(488,360);
	setResizable(false);	
	
        
        vista_control = vista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_panel = new javax.swing.JPanel();
        exit_button = new javax.swing.JButton();
        admin_button = new javax.swing.JButton();
        clinica_label = new javax.swing.JLabel();
        general_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        admin_panel.setBackground(new java.awt.Color(116, 165, 170));
        admin_panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin_panel.setForeground(java.awt.Color.white);
        admin_panel.setMinimumSize(new java.awt.Dimension(488, 360));
        admin_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/exit_.png"))); // NOI18N
        exit_button.setBorder(null);
        exit_button.setContentAreaFilled(false);
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/exitpressed_.png"))); // NOI18N
        exit_button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/exitselected_.png"))); // NOI18N
        exit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_buttonMousePressed(evt);
            }
        });
        admin_panel.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 50, 50));

        admin_button.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        admin_button.setForeground(new java.awt.Color(99, 110, 111));
        admin_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/doctor_.png"))); // NOI18N
        admin_button.setText("Administrar");
        admin_button.setToolTipText("");
        admin_button.setAlignmentY(0.1F);
        admin_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin_button.setIconTextGap(-10);
        admin_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        admin_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        admin_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                admin_buttonMousePressed(evt);
            }
        });
        admin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_buttonActionPerformed(evt);
            }
        });
        admin_panel.add(admin_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 210, 190));

        clinica_label.setBackground(new java.awt.Color(116, 165, 170));
        clinica_label.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        clinica_label.setForeground(new java.awt.Color(227, 227, 227));
        clinica_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/logox__.png"))); // NOI18N
        clinica_label.setText("Clinica X");
        clinica_label.setToolTipText("");
        clinica_label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clinica_label.setOpaque(true);
        admin_panel.add(clinica_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 100));

        general_button.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        general_button.setForeground(new java.awt.Color(99, 110, 111));
        general_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/general_.png"))); // NOI18N
        general_button.setText("Gestión General");
        general_button.setToolTipText("");
        general_button.setAlignmentY(0.1F);
        general_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        general_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        general_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        general_button.setIconTextGap(-10);
        general_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        general_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        general_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                general_buttonMousePressed(evt);
            }
        });
        general_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                general_buttonActionPerformed(evt);
            }
        });
        admin_panel.add(general_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_buttonActionPerformed

    private void general_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_general_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_general_buttonActionPerformed

    private void admin_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("adminUsers");
        
    }//GEN-LAST:event_admin_buttonMousePressed

    private void general_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_general_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("general");
    }//GEN-LAST:event_general_buttonMousePressed

    private void exit_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("login");
    }//GEN-LAST:event_exit_buttonMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_button;
    private javax.swing.JPanel admin_panel;
    private javax.swing.JLabel clinica_label;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton general_button;
    // End of variables declaration//GEN-END:variables
}
