/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controlador.Empleado_Control;
import Controlador.Vista_Control;
import javax.swing.JOptionPane;

/**
 *
 * @author ennuikibun
 */
public class CambiarContrasena extends javax.swing.JFrame {

    Vista_Control vista_control;
    Empleado_Control empleado_control;
    
    public CambiarContrasena(Vista_Control vista) {
        initComponents();
        
        vista_control = vista;
        empleado_control = new Empleado_Control();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cambiarPass_panel = new javax.swing.JPanel();
        back_button1 = new javax.swing.JButton();
        cambiar_pass_button = new javax.swing.JButton();
        clinica_label = new javax.swing.JLabel();
        miContrasena_label = new javax.swing.JLabel();
        myPass_field = new javax.swing.JPasswordField();
        nuevaContra_label = new javax.swing.JLabel();
        nuevaContr_field = new javax.swing.JPasswordField();
        confirmNueva_label = new javax.swing.JLabel();
        confirmContr_field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cambiarPass_panel.setBackground(new java.awt.Color(116, 165, 170));
        cambiarPass_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cambiarPass_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/back_ .png"))); // NOI18N
        back_button1.setBorderPainted(false);
        back_button1.setContentAreaFilled(false);
        back_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button1.setFocusable(false);
        back_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_button1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backpressed_ .png"))); // NOI18N
        back_button1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backselected_ .png"))); // NOI18N
        back_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back_button1MousePressed(evt);
            }
        });
        cambiarPass_panel.add(back_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        cambiar_pass_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/login_.png"))); // NOI18N
        cambiar_pass_button.setBorderPainted(false);
        cambiar_pass_button.setContentAreaFilled(false);
        cambiar_pass_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cambiar_pass_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/loginpressed_.png"))); // NOI18N
        cambiar_pass_button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/loginselected_.png"))); // NOI18N
        cambiar_pass_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiar_pass_buttonMousePressed(evt);
            }
        });
        cambiar_pass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_pass_buttonActionPerformed(evt);
            }
        });
        cambiarPass_panel.add(cambiar_pass_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, 80));

        clinica_label.setBackground(new java.awt.Color(116, 165, 170));
        clinica_label.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        clinica_label.setForeground(new java.awt.Color(227, 227, 227));
        clinica_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/logox__.png"))); // NOI18N
        clinica_label.setToolTipText("");
        clinica_label.setOpaque(true);
        cambiarPass_panel.add(clinica_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 100));

        miContrasena_label.setFont(new java.awt.Font("TakaoPGothic", 1, 15)); // NOI18N
        miContrasena_label.setForeground(new java.awt.Color(227, 227, 227));
        miContrasena_label.setText("Constraseña Actual");
        miContrasena_label.setToolTipText("");
        cambiarPass_panel.add(miContrasena_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        myPass_field.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        cambiarPass_panel.add(myPass_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 170, -1));

        nuevaContra_label.setFont(new java.awt.Font("TakaoPGothic", 1, 15)); // NOI18N
        nuevaContra_label.setForeground(new java.awt.Color(227, 227, 227));
        nuevaContra_label.setText("Nueva Contraseña");
        cambiarPass_panel.add(nuevaContra_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        nuevaContr_field.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        cambiarPass_panel.add(nuevaContr_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, -1));

        confirmNueva_label.setFont(new java.awt.Font("TakaoPGothic", 1, 15)); // NOI18N
        confirmNueva_label.setForeground(new java.awt.Color(227, 227, 227));
        confirmNueva_label.setText("Confirmar Contraseña");
        cambiarPass_panel.add(confirmNueva_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        confirmContr_field.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        cambiarPass_panel.add(confirmContr_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiarPass_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cambiarPass_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cambiar_pass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_pass_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiar_pass_buttonActionPerformed

    private void cambiar_pass_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiar_pass_buttonMousePressed
        String oldpass = myPass_field.getText();
        String newpass = nuevaContr_field.getText();
        String confirmpass = confirmContr_field.getText();
        if(!oldpass.isEmpty() && !newpass.isEmpty() && !confirmpass.isEmpty()){
            String user = vista_control.getUsuario();
            int log = empleado_control.loguearEmpleado(user,oldpass);
            if(log != 0){
                if(newpass.equals(confirmpass)){
                    int res = empleado_control.cambiarContrasenaEmpleado(user, newpass);
                    if(res == 1){
                        JOptionPane.showMessageDialog(null, "La contraseña se ha cambiado correctamente.", "OK!", JOptionPane.INFORMATION_MESSAGE);
                    }else
                        JOptionPane.showMessageDialog(null, "Ha ocurrido un error.\nIntente de nuevo.", "ERROR!", JOptionPane.ERROR_MESSAGE);
                }else
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.\nIntente de nuevo.", "ERROR!", JOptionPane.ERROR_MESSAGE);   
            }else
                JOptionPane.showMessageDialog(null, "Contraseña Antigua Incorrecta", "ALERTA!", JOptionPane.WARNING_MESSAGE);         
        }
        else
           JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "ALERTA!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_cambiar_pass_buttonMousePressed

    private void back_button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MousePressed
        setVisible(false);
        vista_control.mostrarVentana("general");
    }//GEN-LAST:event_back_button1MousePressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button1;
    private javax.swing.JPanel cambiarPass_panel;
    private javax.swing.JButton cambiar_pass_button;
    private javax.swing.JLabel clinica_label;
    private javax.swing.JPasswordField confirmContr_field;
    private javax.swing.JLabel confirmNueva_label;
    private javax.swing.JLabel miContrasena_label;
    private javax.swing.JPasswordField myPass_field;
    private javax.swing.JPasswordField nuevaContr_field;
    private javax.swing.JLabel nuevaContra_label;
    // End of variables declaration//GEN-END:variables
}
