/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controlador.*;
import Logica.*;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ennuikibun
 */
public class CampanasPrevencion extends javax.swing.JFrame {

    Vista_Control vista_control;
    Campana_Control campana_control;
    Asistencia_Control asistencia_control;
    Paciente_Control paciente_control;
    Persona_Control persona_control;
    String var1,var2,var3,var4,var5;
    private static final DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    public CampanasPrevencion(Vista_Control vista) {
        super("Clínica X || Campañas de Prevención");
        initComponents();
          
        setLocationRelativeTo(null);
	setSize(833, 571);
	setResizable(false);	
        
        vista_control = vista;
        campana_control = new Campana_Control();
        asistencia_control = new Asistencia_Control();
        paciente_control = new Paciente_Control();
        persona_control = new Persona_Control();
        agregarAsistente_button.setEnabled(false);
        
        addCombos();
    }
    
    private void addCombos(){
        Vector <String> medicos = new Vector<String>();
        medicos = persona_control.listarMedicos();
        medicoCampana_box.removeAllItems();
        for(int i = 0; i < medicos.size(); i++){
            String m = medicos.get(i);
            medicoCampana_box.addItem(m);
        }
        
        Vector <Campana_Prevencion> campana = new Vector<Campana_Prevencion>();
        campana = campana_control.listarCampanas();
        campana_box.removeAllItems();
        for(int i = 0; i < campana.size(); i++){
            String m = campana.get(i).getNomCampana();
            campana_box.addItem(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campanas_panel = new javax.swing.JPanel();
        campanas_tabbed = new javax.swing.JTabbedPane();
        campana_label = new javax.swing.JPanel();
        registrocam_label = new javax.swing.JLabel();
        nom_label = new javax.swing.JLabel();
        objetivo_label = new javax.swing.JLabel();
        fecha_label = new javax.swing.JLabel();
        dr_label = new javax.swing.JLabel();
        objetivo_scroll = new javax.swing.JScrollPane();
        objetivo_area = new javax.swing.JTextArea();
        nom_field = new javax.swing.JTextField();
        medicoCampana_box = new javax.swing.JComboBox<>();
        campana_date = new com.toedter.calendar.JDateChooser();
        back_button3 = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        registers_scroll = new javax.swing.JScrollPane();
        registers_table = new javax.swing.JTable();
        cod_label = new javax.swing.JLabel();
        cod_field = new javax.swing.JTextField();
        campanas_toolbar = new javax.swing.JToolBar();
        search_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        registros_label = new javax.swing.JLabel();
        todo_button = new javax.swing.JButton();
        asistentes_panel = new javax.swing.JPanel();
        registroAsis_label = new javax.swing.JLabel();
        idPaci_label = new javax.swing.JLabel();
        cod_field1 = new javax.swing.JTextField();
        campa_label = new javax.swing.JLabel();
        campana_box = new javax.swing.JComboBox<>();
        buscarId_button = new javax.swing.JButton();
        agregarAsistente_button = new javax.swing.JButton();
        asistentes_toolbar = new javax.swing.JToolBar();
        search_button1 = new javax.swing.JButton();
        filter_button1 = new javax.swing.JButton();
        clear_button1 = new javax.swing.JButton();
        registers_scroll1 = new javax.swing.JScrollPane();
        registers_table1 = new javax.swing.JTable();
        registros_label1 = new javax.swing.JLabel();
        back_button4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campanas_panel.setBackground(new java.awt.Color(116, 165, 170));
        campanas_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        campanas_tabbed.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        campanas_tabbed.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        registrocam_label.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        registrocam_label.setText("Registrar Campaña");

        nom_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        nom_label.setText("Nombre");

        objetivo_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        objetivo_label.setText("Objetivo");

        fecha_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        fecha_label.setText("Fecha");

        dr_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        dr_label.setText("Dr. a Cargo");

        objetivo_area.setColumns(20);
        objetivo_area.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        objetivo_area.setRows(5);
        objetivo_scroll.setViewportView(objetivo_area);

        nom_field.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        medicoCampana_box.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        campana_date.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        back_button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/back_ .png"))); // NOI18N
        back_button3.setBorderPainted(false);
        back_button3.setContentAreaFilled(false);
        back_button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button3.setFocusable(false);
        back_button3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_button3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backpressed_ .png"))); // NOI18N
        back_button3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backselected_ .png"))); // NOI18N
        back_button3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back_button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back_button3MousePressed(evt);
            }
        });

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/save_.png"))); // NOI18N
        save_button.setBorderPainted(false);
        save_button.setContentAreaFilled(false);
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/savepressed_.png"))); // NOI18N
        save_button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/saveselected_.png"))); // NOI18N
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        registers_table.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        registers_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombre", "Objetivo", "Médico Encargado", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        registers_scroll.setViewportView(registers_table);
        if (registers_table.getColumnModel().getColumnCount() > 0) {
            registers_table.getColumnModel().getColumn(4).setMinWidth(80);
            registers_table.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        cod_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        cod_label.setText("Código");

        cod_field.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        campanas_toolbar.setBackground(new java.awt.Color(132, 182, 188));
        campanas_toolbar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campanas_toolbar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        campanas_toolbar.setRollover(true);
        campanas_toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campanas_toolbarMousePressed(evt);
            }
        });

        search_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        search_button.setForeground(new java.awt.Color(99, 110, 111));
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/search_.png"))); // NOI18N
        search_button.setToolTipText("");
        search_button.setAlignmentY(0.1F);
        search_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_button.setIconTextGap(5);
        search_button.setMaximumSize(new java.awt.Dimension(129, 129));
        search_button.setMinimumSize(new java.awt.Dimension(129, 129));
        search_button.setName("doctor_button"); // NOI18N
        search_button.setPreferredSize(new java.awt.Dimension(129, 53));
        search_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                search_buttonMousePressed(evt);
            }
        });
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        campanas_toolbar.add(search_button);

        clear_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        clear_button.setForeground(new java.awt.Color(99, 110, 111));
        clear_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/clear_.png"))); // NOI18N
        clear_button.setToolTipText("");
        clear_button.setAlignmentY(0.1F);
        clear_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_button.setFocusable(false);
        clear_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear_button.setIconTextGap(5);
        clear_button.setMaximumSize(new java.awt.Dimension(129, 129));
        clear_button.setMinimumSize(new java.awt.Dimension(129, 129));
        clear_button.setName("doctor_button"); // NOI18N
        clear_button.setPreferredSize(new java.awt.Dimension(129, 53));
        clear_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clear_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clear_buttonMousePressed(evt);
            }
        });
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        campanas_toolbar.add(clear_button);

        registros_label.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        registros_label.setText("Registros");

        todo_button.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        todo_button.setForeground(new java.awt.Color(99, 110, 111));
        todo_button.setText("Mostrar Todo");
        todo_button.setToolTipText("");
        todo_button.setAlignmentY(0.1F);
        todo_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        todo_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        todo_button.setFocusable(false);
        todo_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        todo_button.setIconTextGap(5);
        todo_button.setMaximumSize(new java.awt.Dimension(129, 129));
        todo_button.setMinimumSize(new java.awt.Dimension(129, 129));
        todo_button.setName("doctor_button"); // NOI18N
        todo_button.setPreferredSize(new java.awt.Dimension(53, 53));
        todo_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        todo_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                todo_buttonMousePressed(evt);
            }
        });
        todo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todo_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout campana_labelLayout = new javax.swing.GroupLayout(campana_label);
        campana_label.setLayout(campana_labelLayout);
        campana_labelLayout.setHorizontalGroup(
            campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campana_labelLayout.createSequentialGroup()
                .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campana_labelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(dr_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicoCampana_box, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(campana_labelLayout.createSequentialGroup()
                            .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(campana_labelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(registrocam_label))
                                .addGroup(campana_labelLayout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fecha_label)
                                        .addComponent(objetivo_label)
                                        .addComponent(cod_label))
                                    .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(campana_labelLayout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(cod_field, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(151, 151, 151)
                                            .addComponent(nom_label)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nom_field, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campana_labelLayout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(campana_date, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(objetivo_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(189, 189, 189)
                                            .addComponent(save_button)
                                            .addGap(70, 70, 70)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back_button3))
                        .addGroup(campana_labelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registros_label)
                                .addGroup(campana_labelLayout.createSequentialGroup()
                                    .addComponent(registers_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campanas_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(todo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(77, 77, 77))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        campana_labelLayout.setVerticalGroup(
            campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(campana_labelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(campana_labelLayout.createSequentialGroup()
                        .addComponent(registrocam_label)
                        .addGap(16, 16, 16)
                        .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cod_label)
                            .addComponent(cod_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom_label)
                            .addComponent(nom_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicoCampana_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dr_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objetivo_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(objetivo_label)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campana_labelLayout.createSequentialGroup()
                        .addComponent(back_button3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save_button)))
                .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campana_labelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(fecha_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(campana_labelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campana_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registros_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(campana_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(campana_labelLayout.createSequentialGroup()
                        .addComponent(registers_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, campana_labelLayout.createSequentialGroup()
                        .addComponent(campanas_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(todo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );

        campanas_tabbed.addTab("Campañas", campana_label);

        registroAsis_label.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        registroAsis_label.setText("Registrar Asistente");

        idPaci_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        idPaci_label.setText("Id Paciente");

        cod_field1.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        campa_label.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        campa_label.setText("Campaña");

        campana_box.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N

        buscarId_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        buscarId_button.setForeground(new java.awt.Color(99, 110, 111));
        buscarId_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/searchid_.png"))); // NOI18N
        buscarId_button.setToolTipText("");
        buscarId_button.setAlignmentY(0.1F);
        buscarId_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarId_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarId_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarId_button.setIconTextGap(5);
        buscarId_button.setMaximumSize(new java.awt.Dimension(129, 129));
        buscarId_button.setMinimumSize(new java.awt.Dimension(129, 129));
        buscarId_button.setName("doctor_button"); // NOI18N
        buscarId_button.setPreferredSize(new java.awt.Dimension(129, 53));
        buscarId_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarId_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarId_buttonMousePressed(evt);
            }
        });
        buscarId_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarId_buttonActionPerformed(evt);
            }
        });

        agregarAsistente_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        agregarAsistente_button.setForeground(new java.awt.Color(99, 110, 111));
        agregarAsistente_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/agregar_.png"))); // NOI18N
        agregarAsistente_button.setToolTipText("");
        agregarAsistente_button.setAlignmentY(0.1F);
        agregarAsistente_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarAsistente_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarAsistente_button.setFocusable(false);
        agregarAsistente_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregarAsistente_button.setIconTextGap(5);
        agregarAsistente_button.setMaximumSize(new java.awt.Dimension(129, 129));
        agregarAsistente_button.setMinimumSize(new java.awt.Dimension(129, 129));
        agregarAsistente_button.setName("doctor_button"); // NOI18N
        agregarAsistente_button.setPreferredSize(new java.awt.Dimension(53, 53));
        agregarAsistente_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarAsistente_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarAsistente_buttonMousePressed(evt);
            }
        });
        agregarAsistente_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAsistente_buttonActionPerformed(evt);
            }
        });

        asistentes_toolbar.setBackground(new java.awt.Color(132, 182, 188));
        asistentes_toolbar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        asistentes_toolbar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        asistentes_toolbar.setRollover(true);
        asistentes_toolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                asistentes_toolbarMousePressed(evt);
            }
        });

        search_button1.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        search_button1.setForeground(new java.awt.Color(99, 110, 111));
        search_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/search_.png"))); // NOI18N
        search_button1.setToolTipText("");
        search_button1.setAlignmentY(0.1F);
        search_button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search_button1.setIconTextGap(5);
        search_button1.setMaximumSize(new java.awt.Dimension(129, 129));
        search_button1.setMinimumSize(new java.awt.Dimension(129, 129));
        search_button1.setName("doctor_button"); // NOI18N
        search_button1.setPreferredSize(new java.awt.Dimension(129, 53));
        search_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        search_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                search_button1MousePressed(evt);
            }
        });
        search_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_button1ActionPerformed(evt);
            }
        });
        asistentes_toolbar.add(search_button1);

        filter_button1.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        filter_button1.setForeground(new java.awt.Color(99, 110, 111));
        filter_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/filter_.png"))); // NOI18N
        filter_button1.setToolTipText("");
        filter_button1.setAlignmentY(0.1F);
        filter_button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        filter_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filter_button1.setFocusable(false);
        filter_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filter_button1.setIconTextGap(5);
        filter_button1.setMaximumSize(new java.awt.Dimension(129, 129));
        filter_button1.setMinimumSize(new java.awt.Dimension(129, 129));
        filter_button1.setName("doctor_button"); // NOI18N
        filter_button1.setPreferredSize(new java.awt.Dimension(129, 53));
        filter_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        filter_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                filter_button1MousePressed(evt);
            }
        });
        filter_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_button1ActionPerformed(evt);
            }
        });
        asistentes_toolbar.add(filter_button1);

        clear_button1.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        clear_button1.setForeground(new java.awt.Color(99, 110, 111));
        clear_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/clear_.png"))); // NOI18N
        clear_button1.setToolTipText("");
        clear_button1.setAlignmentY(0.1F);
        clear_button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_button1.setFocusable(false);
        clear_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear_button1.setIconTextGap(5);
        clear_button1.setMaximumSize(new java.awt.Dimension(129, 129));
        clear_button1.setMinimumSize(new java.awt.Dimension(129, 129));
        clear_button1.setName("doctor_button"); // NOI18N
        clear_button1.setPreferredSize(new java.awt.Dimension(129, 53));
        clear_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clear_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clear_button1MousePressed(evt);
            }
        });
        clear_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_button1ActionPerformed(evt);
            }
        });
        asistentes_toolbar.add(clear_button1);

        registers_table1.setFont(new java.awt.Font("Lucida Bright", 0, 15)); // NOI18N
        registers_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Paciente", "Campaña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        registers_scroll1.setViewportView(registers_table1);

        registros_label1.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        registros_label1.setText("Registros");

        back_button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/back_ .png"))); // NOI18N
        back_button4.setBorderPainted(false);
        back_button4.setContentAreaFilled(false);
        back_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button4.setFocusable(false);
        back_button4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_button4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backpressed_ .png"))); // NOI18N
        back_button4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backselected_ .png"))); // NOI18N
        back_button4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back_button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back_button4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout asistentes_panelLayout = new javax.swing.GroupLayout(asistentes_panel);
        asistentes_panel.setLayout(asistentes_panelLayout);
        asistentes_panelLayout.setHorizontalGroup(
            asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asistentes_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asistentes_panelLayout.createSequentialGroup()
                        .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroAsis_label)
                            .addGroup(asistentes_panelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idPaci_label)
                                    .addComponent(campa_label))
                                .addGap(32, 32, 32)
                                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(asistentes_panelLayout.createSequentialGroup()
                                        .addComponent(cod_field1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buscarId_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campana_box, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addComponent(agregarAsistente_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_button4))
                    .addGroup(asistentes_panelLayout.createSequentialGroup()
                        .addComponent(registros_label1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(asistentes_panelLayout.createSequentialGroup()
                        .addComponent(registers_scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(asistentes_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        asistentes_panelLayout.setVerticalGroup(
            asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asistentes_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asistentes_panelLayout.createSequentialGroup()
                        .addComponent(registroAsis_label)
                        .addGap(16, 16, 16)
                        .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(asistentes_panelLayout.createSequentialGroup()
                                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idPaci_label)
                                    .addComponent(cod_field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campa_label)
                                    .addComponent(campana_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buscarId_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(asistentes_panelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(agregarAsistente_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(back_button4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(registros_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(asistentes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registers_scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asistentes_panelLayout.createSequentialGroup()
                        .addComponent(asistentes_toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addContainerGap())
        );

        campanas_tabbed.addTab("Asistentes", asistentes_panel);

        javax.swing.GroupLayout campanas_panelLayout = new javax.swing.GroupLayout(campanas_panel);
        campanas_panel.setLayout(campanas_panelLayout);
        campanas_panelLayout.setHorizontalGroup(
            campanas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campanas_tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        campanas_panelLayout.setVerticalGroup(
            campanas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campanas_tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campanas_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(campanas_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMousePressed
        DefaultTableModel model = (DefaultTableModel) registers_table.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Campana_Prevencion campana = new Campana_Prevencion();
        int cod = Integer.parseInt(JOptionPane.showInputDialog(null, "Inserte código de la Campaña", ""));
        campana = campana_control.consultarCampana(cod);
        if(campana != null){
            String nombre = campana.getNomCampana();
            String objetivo = campana.getObjetCampana();
            String medico = persona_control.consultarPersona(campana.getMedicoEncargado()).getNombre();
            String fecha = campana.getFechaCampana();
            
            model.addRow(new Object[]{cod, nombre, objetivo, medico, fecha});  
        }
        else
            JOptionPane.showMessageDialog(null, "Error. \n Verifique el número de Identidad del Paciente.");
    }//GEN-LAST:event_search_buttonMousePressed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_buttonActionPerformed

    private void clear_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_buttonMousePressed
        DefaultTableModel model = (DefaultTableModel) registers_table.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_clear_buttonMousePressed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void campanas_toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campanas_toolbarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campanas_toolbarMousePressed

    private void buscarId_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarId_buttonMousePressed
        if(!cod_field1.getText().isEmpty()){
            int id = Integer.parseInt(cod_field1.getText());
            Paciente paciente = new Paciente();
            paciente = paciente_control.consultarPaciente(id);
            if(paciente != null){
                addCombos();
                agregarAsistente_button.setEnabled(true);
                campana_box.setEnabled(true);
            }else{
               JOptionPane.showMessageDialog(null, "No se encontró ningún paciente.", "ALERTA!", JOptionPane.WARNING_MESSAGE);
            }
            
        }else
            JOptionPane.showMessageDialog(null, "El campo Id es necesario.", "ALERTA!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_buscarId_buttonMousePressed

    private void buscarId_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarId_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarId_buttonActionPerformed

    private void agregarAsistente_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarAsistente_buttonMousePressed
        Campana_Prevencion campana = new Campana_Prevencion();
        var1 = cod_field1.getText();
        var2 = campana_box.getSelectedItem().toString();
        if(!var1.isEmpty() && !var2.isEmpty()){
            campana = campana_control.consultarxNombre(var2);
            int numFilas = asistencia_control.insertarAsistencia(campana.getCodCampana(),Integer.parseInt(var1));
            if(numFilas == 1){
                JOptionPane.showMessageDialog(null, "El paciente se ha registrado como asistente exitósamente.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error.\nIntente de nuevo.", "ERROR!", JOptionPane.ERROR_MESSAGE);
                campana_box.setEnabled(false);
            }
            agregarAsistente_button.setEnabled(false);
        }else
            JOptionPane.showMessageDialog(null, "Datos Inválidos", "ALERTA!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_agregarAsistente_buttonMousePressed

    private void agregarAsistente_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAsistente_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarAsistente_buttonActionPerformed

    private void search_button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_button1MousePressed
        DefaultTableModel model = (DefaultTableModel) registers_table1.getModel();
        Vector<Asistencia_Campana> asistencia = new Vector<Asistencia_Campana>();
        int id_pac = Integer.parseInt(JOptionPane.showInputDialog(null, "Inserte Id del Paciente", ""));
        asistencia = asistencia_control.listarAsistencias(id_pac);
        if(!asistencia.isEmpty()){
            for(int i=0;i<asistencia.size();i++){
                String nombre = persona_control.consultarPersona(id_pac).getNombre();
                String nomCampana = campana_control.consultarCampana(asistencia.get(i).getCampana()).getNomCampana();
                
                model.addRow(new Object[]{id_pac, nombre, nomCampana}); 
            }
 
        }
        else
            JOptionPane.showMessageDialog(null, "Error. \n No se encontró el Paciente.");
    }//GEN-LAST:event_search_button1MousePressed

    private void search_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_button1ActionPerformed

    private void filter_button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filter_button1MousePressed
        DefaultTableModel model = (DefaultTableModel) registers_table1.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        registers_table1.setModel(model);
        Vector <Asistencia_Campana> asistencias = new Vector <Asistencia_Campana>();
        String[] campanas = new String[campana_control.listarCampanas().size()];
        for(int i=0; i< campanas.length; i++){
            campanas[i] = campana_control.listarCampanas().get(i).getNomCampana();
        }
        String filtro = (String) JOptionPane.showInputDialog(null, "Seleccione una Campaña:", "FILTRAR", JOptionPane.DEFAULT_OPTION,null,campanas, campanas[0]);
        Campana_Prevencion campana = new Campana_Prevencion();
        campana = campana_control.consultarxNombre(filtro);
        int codCampana = campana.getCodCampana();
        asistencias = asistencia_control.filtrarAsistencias(codCampana);
        if(!asistencias.isEmpty()){
            for(int i = 0; i< asistencias.size(); i++){
                int id_pac = asistencias.get(i).getPaciente();
                String nom_pac = persona_control.consultarPersona(id_pac).getNombre();
                String nom_cam = campana_control.consultarCampana(codCampana).getNomCampana();
                model.addRow(new Object[]{id_pac, nom_pac, nom_cam}); 
            }     
        }
        else
            JOptionPane.showMessageDialog(null, "La Campaña no existe O no tiene asistentes todavía.");
    }//GEN-LAST:event_filter_button1MousePressed

    private void filter_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_button1ActionPerformed

    private void clear_button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_button1MousePressed
        DefaultTableModel model = (DefaultTableModel) registers_table1.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_clear_button1MousePressed

    private void clear_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_button1ActionPerformed

    private void asistentes_toolbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asistentes_toolbarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_asistentes_toolbarMousePressed

    private void back_button3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button3MousePressed
        setVisible(false);
        vista_control.mostrarVentana("general");
    }//GEN-LAST:event_back_button3MousePressed

    private void back_button4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button4MousePressed
        setVisible(false);
        vista_control.mostrarVentana("general");
    }//GEN-LAST:event_back_button4MousePressed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        Campana_Prevencion campana = new Campana_Prevencion();
        var1 = cod_field.getText();
        var2 = nom_field.getText();
        var3 = medicoCampana_box.getSelectedItem().toString();
        var4 = objetivo_area.getText();
        Date fecha = new Date();
        fecha = campana_date.getDate();
        var5 = sdf.format(fecha);
        if(!var1.isEmpty() && !var2.isEmpty() && !var3.isEmpty() && !var4.isEmpty() && !var5.isEmpty()){
            int id_med = persona_control.idMedico(var3);
            int numFilas = campana_control.insertarCampana(Integer.parseInt(var1), var2, var4, var5, id_med);
            if(numFilas == 1){
                JOptionPane.showMessageDialog(null, "La campaña se ha registrado exitósamente.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error.\nIntente de nuevo.", "ERROR!", JOptionPane.ERROR_MESSAGE);
                campana_box.setEnabled(false);
            }
        }else
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "ALERTA!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_save_buttonActionPerformed

    private void todo_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todo_buttonMousePressed
        Vector<Campana_Prevencion> campanas = new Vector<Campana_Prevencion>();
        DefaultTableModel model = (DefaultTableModel) registers_table.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        campanas = campana_control.listarCampanas();
        if(!campanas.isEmpty()){
            for(int i=0; i<campanas.size(); i++){
                String nombre = campanas.get(i).getNomCampana();
            String objetivo = campanas.get(i).getObjetCampana();
            String medico = persona_control.consultarPersona(campanas.get(i).getMedicoEncargado()).getNombre();
            String fecha = campanas.get(i).getFechaCampana();
            int cod = campanas.get(i).getCodCampana();
            model.addRow(new Object[]{cod, nombre, objetivo, medico, fecha}); 
            }
        }else
        JOptionPane.showMessageDialog(null, "No  Hay Campañas todavía.", "ALERTA!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_todo_buttonMousePressed

    private void todo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todo_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todo_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAsistente_button;
    private javax.swing.JPanel asistentes_panel;
    private javax.swing.JToolBar asistentes_toolbar;
    private javax.swing.JButton back_button3;
    private javax.swing.JButton back_button4;
    private javax.swing.JButton buscarId_button;
    private javax.swing.JLabel campa_label;
    private javax.swing.JComboBox<String> campana_box;
    private com.toedter.calendar.JDateChooser campana_date;
    private javax.swing.JPanel campana_label;
    private javax.swing.JPanel campanas_panel;
    private javax.swing.JTabbedPane campanas_tabbed;
    private javax.swing.JToolBar campanas_toolbar;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton clear_button1;
    private javax.swing.JTextField cod_field;
    private javax.swing.JTextField cod_field1;
    private javax.swing.JLabel cod_label;
    private javax.swing.JLabel dr_label;
    private javax.swing.JLabel fecha_label;
    private javax.swing.JButton filter_button1;
    private javax.swing.JLabel idPaci_label;
    private javax.swing.JComboBox<String> medicoCampana_box;
    private javax.swing.JTextField nom_field;
    private javax.swing.JLabel nom_label;
    private javax.swing.JTextArea objetivo_area;
    private javax.swing.JLabel objetivo_label;
    private javax.swing.JScrollPane objetivo_scroll;
    private javax.swing.JScrollPane registers_scroll;
    private javax.swing.JScrollPane registers_scroll1;
    private javax.swing.JTable registers_table;
    private javax.swing.JTable registers_table1;
    private javax.swing.JLabel registroAsis_label;
    private javax.swing.JLabel registrocam_label;
    private javax.swing.JLabel registros_label;
    private javax.swing.JLabel registros_label1;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JButton search_button1;
    private javax.swing.JButton todo_button;
    // End of variables declaration//GEN-END:variables
}
