/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controlador.Vista_Control;

/**
 *
 * @author ennuikibun
 */
public class General extends javax.swing.JFrame {

    Vista_Control vista_control;
    
    public General(Vista_Control vista) {
        super("Clínica X || Administración General");
        initComponents();
	setLocationRelativeTo(null);
	setSize(723, 588);
	//setResizable(false);	
        setVisible(false);
	
        
        vista_control = vista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        general_panel = new javax.swing.JPanel();
        clinica_label = new javax.swing.JLabel();
        agenda_button = new javax.swing.JButton();
        meds_button = new javax.swing.JButton();
        campaign_button = new javax.swing.JButton();
        conf_button = new javax.swing.JButton();
        patient_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        general_panel.setBackground(new java.awt.Color(116, 165, 170));
        general_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        general_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clinica_label.setBackground(new java.awt.Color(116, 165, 170));
        clinica_label.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        clinica_label.setForeground(new java.awt.Color(227, 227, 227));
        clinica_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/logox__.png"))); // NOI18N
        clinica_label.setText("Clinica X");
        clinica_label.setToolTipText("");
        clinica_label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clinica_label.setOpaque(true);
        clinica_label.setPreferredSize(new java.awt.Dimension(680, 102));
        general_panel.add(clinica_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 100));

        agenda_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        agenda_button.setForeground(new java.awt.Color(99, 110, 111));
        agenda_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/agenda_.png"))); // NOI18N
        agenda_button.setText("Agenda");
        agenda_button.setToolTipText("");
        agenda_button.setAlignmentY(0.1F);
        agenda_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agenda_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agenda_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agenda_button.setIconTextGap(5);
        agenda_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        agenda_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agenda_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agenda_buttonMousePressed(evt);
            }
        });
        agenda_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenda_buttonActionPerformed(evt);
            }
        });
        general_panel.add(agenda_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 210, 190));

        meds_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        meds_button.setForeground(new java.awt.Color(99, 110, 111));
        meds_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/medicine_.png"))); // NOI18N
        meds_button.setText("Medicamentos");
        meds_button.setToolTipText("");
        meds_button.setAlignmentY(0.1F);
        meds_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        meds_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meds_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        meds_button.setIconTextGap(5);
        meds_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        meds_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        meds_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meds_buttonActionPerformed(evt);
            }
        });
        general_panel.add(meds_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 210, 190));

        campaign_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        campaign_button.setForeground(new java.awt.Color(99, 110, 111));
        campaign_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/campaign_.png"))); // NOI18N
        campaign_button.setText("Campañas Preventivas");
        campaign_button.setToolTipText("");
        campaign_button.setAlignmentY(0.1F);
        campaign_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campaign_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campaign_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        campaign_button.setIconTextGap(5);
        campaign_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        campaign_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        campaign_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campaign_buttonMousePressed(evt);
            }
        });
        campaign_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campaign_buttonActionPerformed(evt);
            }
        });
        general_panel.add(campaign_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 210, 190));

        conf_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        conf_button.setForeground(new java.awt.Color(99, 110, 111));
        conf_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/conf_.png"))); // NOI18N
        conf_button.setText("Cambiar Contraseña");
        conf_button.setToolTipText("");
        conf_button.setAlignmentY(0.1F);
        conf_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        conf_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conf_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        conf_button.setIconTextGap(-10);
        conf_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        conf_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        conf_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conf_buttonMousePressed(evt);
            }
        });
        conf_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_buttonActionPerformed(evt);
            }
        });
        general_panel.add(conf_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 210, 190));

        patient_button.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        patient_button.setForeground(new java.awt.Color(99, 110, 111));
        patient_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/patient_.png"))); // NOI18N
        patient_button.setText("Pacientes");
        patient_button.setToolTipText("");
        patient_button.setAlignmentY(0.1F);
        patient_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patient_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        patient_button.setIconTextGap(5);
        patient_button.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        patient_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        patient_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patient_buttonMousePressed(evt);
            }
        });
        patient_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_buttonActionPerformed(evt);
            }
        });
        general_panel.add(patient_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 190));

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/exit_.png"))); // NOI18N
        exit_button.setBorder(null);
        exit_button.setContentAreaFilled(false);
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/exitpressed_.png"))); // NOI18N
        exit_button.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/exitselected_.png"))); // NOI18N
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        general_panel.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(general_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(general_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agenda_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenda_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agenda_buttonActionPerformed

    private void meds_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meds_buttonActionPerformed
        // TODO add your handling code here:
	    setVisible(false);
            vista_control.mostrarVentana("medicamentos");
    }//GEN-LAST:event_meds_buttonActionPerformed

    private void campaign_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campaign_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campaign_buttonActionPerformed

    private void conf_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_buttonActionPerformed

    private void patient_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patient_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        setVisible(false);
        vista_control.mostrarVentana("login");
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void patient_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("pacientes");
    }//GEN-LAST:event_patient_buttonMousePressed

    private void agenda_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agenda_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("agendamiento");
    }//GEN-LAST:event_agenda_buttonMousePressed

    private void campaign_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campaign_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("campanas");
    }//GEN-LAST:event_campaign_buttonMousePressed

    private void conf_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conf_buttonMousePressed
        setVisible(false);
        vista_control.mostrarVentana("cambiarCont");
    }//GEN-LAST:event_conf_buttonMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agenda_button;
    private javax.swing.JButton campaign_button;
    private javax.swing.JLabel clinica_label;
    private javax.swing.JButton conf_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JPanel general_panel;
    private javax.swing.JButton meds_button;
    private javax.swing.JButton patient_button;
    // End of variables declaration//GEN-END:variables
}
