/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controlador.*;
import Logica.Medicamento;
import Logica.Paciente;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document; 
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.util.Vector;
import javax.swing.JOptionPane;



/**
 *
 * @author daniel
 */
public class Medicamentos extends javax.swing.JFrame {
    
    Paciente_Control paciente_control;
    Medico_Control medico_control; 
    Medicamento_Control medicamento_control;
    Formulacion_Control formulacion_control; 
    Formula_Control formula_control; 
    Vista_Control vista_control; 
    Medicamento medicamento; 
    /**
     * Creates new form Medicamentos
     */
    public Medicamentos(Vista_Control vista ) {
        initComponents();
        
        vista_control = vista; 
        paciente_control = new Paciente_Control();
        medico_control= new Medico_Control(); 
        medicamento_control = new Medicamento_Control(); 
        formulacion_control = new Formulacion_Control(); 
        formula_control = new Formula_Control();
        
        medicamento =new Medicamento(); 
        
        setLocationRelativeTo(null);
	setSize(630, 600);
	setResizable(false);	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        general_panel = new javax.swing.JPanel();
        clinica_label = new javax.swing.JLabel();
        jPanelRegistrar = new javax.swing.JPanel();
        jTextFieldDescr = new javax.swing.JTextField();
        jTextFieldCosto = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableQuery = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        back_button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        general_panel.setBackground(new java.awt.Color(116, 165, 170));
        general_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        general_panel.setPreferredSize(new java.awt.Dimension(1230, 610));
        general_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clinica_label.setBackground(new java.awt.Color(116, 165, 170));
        clinica_label.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        clinica_label.setForeground(new java.awt.Color(227, 227, 227));
        clinica_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/logox__.png"))); // NOI18N
        clinica_label.setText("Clinica X");
        clinica_label.setToolTipText("");
        clinica_label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clinica_label.setOpaque(true);
        clinica_label.setPreferredSize(new java.awt.Dimension(680, 102));
        general_panel.add(clinica_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 100));

        jPanelRegistrar.setBackground(new java.awt.Color(116, 165, 170));
        jPanelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelRegistrar.add(jTextFieldDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, -1));
        jPanelRegistrar.add(jTextFieldCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelRegistrar.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, -1));

        jLabel5.setText("Descripción");
        jPanelRegistrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        jLabel6.setText("Costo");
        jPanelRegistrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 30));

        jLabel7.setText("Nombre Med");
        jPanelRegistrar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/savecita_.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelRegistrar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/search_.png"))); // NOI18N
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanelRegistrar.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 40, 40));

        jTableQuery.setBackground(new java.awt.Color(150, 165, 170));
        jTableQuery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Medicamento", "Descripción", "Costo"
            }
        ));
        jScrollPane4.setViewportView(jTableQuery);

        jPanelRegistrar.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 505, 300));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/med__.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelRegistrar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 110, 100));

        back_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/back_ .png"))); // NOI18N
        back_button1.setBorderPainted(false);
        back_button1.setContentAreaFilled(false);
        back_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back_button1.setFocusable(false);
        back_button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_button1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backpressed_ .png"))); // NOI18N
        back_button1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui/imgs/backselected_ .png"))); // NOI18N
        back_button1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        back_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back_button1MousePressed(evt);
            }
        });
        jPanelRegistrar.add(back_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        general_panel.add(jPanelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 500));

        getContentPane().add(general_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if(!jTextFieldNombre.getText().isEmpty() &&!jTextFieldDescr.getText().isEmpty() &&!jTextFieldCosto.getText().isEmpty() )
        {
            medicamento_control.insertarMedicamento(jTextFieldNombre.getText(), jTextFieldDescr.getText(), Integer.parseInt(jTextFieldCosto.getText()));
            JOptionPane.showMessageDialog(null, "Medicamento Registrado con Éxito.", "Éxito!", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
              JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "ALERTA!", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void back_button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MousePressed
        setVisible(false);
        vista_control.mostrarVentana("general");
    }//GEN-LAST:event_back_button1MousePressed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableQuery.getModel();
        
        if(model.getRowCount() != 0 )
        {
            int rows= model.getRowCount(); 
            for(int i= 0; i <rows; i++) {
                
                model.removeRow(0);
             }
        }      
        if (!jTextFieldNombre.getText().isEmpty())
        {
            Vector <Medicamento> meds = new Vector <Medicamento> (); 
            meds = medicamento_control.buscarxNombre(jTextFieldNombre.getText());
            for (int i= 0; i < meds.size() ; i++)
            {
                model.addRow(new Object[]{meds.get(i).getCodigoMedicamento(), meds.get(i).getNomMedicamento() , meds.get(i).getDescrip_medicamento(), meds.get(i).getCosto_medicamento()});   
            }
        }
            
            
    }//GEN-LAST:event_jButtonSearchActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button1;
    private javax.swing.JLabel clinica_label;
    private javax.swing.JPanel general_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelRegistrar;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableQuery;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldDescr;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
